  library(stats)
  library(dplyr) 
  library(tidyr)
  library(mice)
  library(tidyverse)
  library(modelr)     
  library(broom) 
  library(car)
  library(naniar)
  library(janitor)
  library(onewaytests)
  library(sinkr)

load("~/Desktop/R_hands_on/Search engine/sales_ah_1Y_[all_states].Rda")
